name: Validate Code
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        shell: bash
        run: |
          echo 'GITHUB_CONTEXT: ${{ toJSON(github) }}'
          echo 'Github event ref: ${{ github.event.ref }}'
          echo 'Github event ref change: ${{ github.event.ref = "test" }}'
          echo 'Github event ref: ${{ github.event.ref }}'