name: Validate Code
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send a notification
        run: echo "The code is being validated"
  run-unit-tests:
    needs: send-notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run unit tests
        run: mvn test
  send-confirmation:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Send a notification
        run: echo "The code has been validated"