name: Validate Code
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        shell: bash
        env:
          GITHUB_REF: "refs/heads/${{ github.base_ref }}"
        run: |
          echo "GITHUB_CONTEXT: $GITHUB_REF"
          echo "refs/heads/${{ github.base_ref }}"
          echo 'Github context: ${{ toJson(github) }}'